version: '3.1'

services:
    app:
        #build:
            #context: .
            #dockerfile: .docker/Dockerfile
        image: 'restapi-laravel:v1'
        container_name: laravel-app
        ports:
            - "8080:80"
        volumes:
            - ./:/var/www/html
        networks:
            - laravel-network
        depends_on:
            - mysql
    mysql:
        image: 'mariadb:latest'
        container_name: laravel-db
        restart: unless-stopped
        ports:
            - "3306:3306"
        environment:
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
            MYSQL_PASSWORD: ${DB_PASSWORD}
            MYSQL_USER: ${DB_USERNAME}
            MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
        volumes:
            - ./database/dbdata:/var/lib/mysql
        networks:
            - laravel-network

networks:
    laravel-network:
        driver: bridge