version: '3.1'

services:
    app:
        build:
            context: .
            dockerfile: .docker/Dockerfile
        
        container_name: laravel-app
        restart: unless-stopped
        ports:
            - "8000:80"
        volumes:
            - ./app:/var/www/html
        networks:
            - laravel-network
        depends_on:
            - mysql

    
    mysql:
        image: 'mariadb:latest'
        container_name: laravel-db
        restart: unless-stopped
        ports:
            - "3306:3306"
        environment:
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
            MYSQL_PASSWORD: ${DB_PASSWORD}
            MYSQL_USER: ${DB_USERNAME}
            MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
        volumes:
            - ./database/dbdata:/var/lib/mysql
        networks:
            - laravel-network
    
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        restart: always
        depends_on:
            - mysql
        environment:
            - PMA_HOST=mysql
            - MYSQL_ROOT_PASSWORD=root
        ports:
            - 8082:80
        networks:
        - laravel-network

networks:
    laravel-network:
        driver: bridge